/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend2;

import backend2.controller.Controller;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        Controller c = new Controller();
        c.go();
    }
}
