/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package river;

import river.controller.Controller;

public class App {
  
    public static void main(String[] args) {
        Controller c = new Controller();
        c.go();
    }
}
